config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  root 'posts#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'search', to: 'posts#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    
    validates :title, presence: true
    validates :tutor_area, presence: true
    validates :schedule, presence: true
    validates :description, presence: true
    validates :price, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }

    def self.search(pattern)
        if pattern.blank?  # blank? covers both nil and empty string
          all
        else
          where('description LIKE ?', "%#{pattern}%")
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.user_email = user_email.downcase }
    has_many :posts
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
     
    validates :username, presence: true, length: { minimum: 3, maximum: 25 }, uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6, maximum: 25 }
    validates :user_email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
    validates :fullname, presence: true, length: { minimum: 3, maximum: 25 }
    
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    
    
    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
      
    def logged_in?
        !!current_user
    end
    
    def require_user
        if !logged_in?
            flash[:notice] = "You are logged in"
            redirect_to login_path
        end
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    # redirect_to posts_path if logged_in?
  end

  def about
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index, :search, :home]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all
  end

  def home
    @posts = Post.all
  end
  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end
  
  def search
    keyword = params[:keyword].downcase
    @posts = Post.all
    @posts = Post.where("lower(title) like ?", "%#{keyword}%")
      .or(Post.where("lower(description) like ?", "%#{keyword}%"))
      .or(Post.where("lower(tutor_area) like ?", "%#{keyword}%"))
      .or(Post.where("lower(schedule) like ?", "%#{keyword}%"))
    @users = User.all
    @users = User.where("lower(username) like ?", "%#{keyword}%")
    .or(User.where("lower(fullname) like ?", "%#{keyword}%"))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.fetch(:post, {}).permit(:title, :tutor_area, :schedule, :description, :price)
    end
    
    def require_same_user
      if current_user != @post.user
        flash[:notice] = "You can only edit or delete your posts"
        redirect_to @post
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
    
    def create
        user = User.find_by(user_email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to posts_path
        else
            flash.now[:alert] = "There was something wrong with your login details"
            render 'new'
        end
    end
    
    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update]
    skip_before_action :verify_authenticity_token
    
    def show
        @posts = @user.posts
    end
    
    def index
        @users = User.all
    end
    
    def new
        @user = User.new
    end
    
    def edit
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Profile was created successfully."
            redirect_to @user
        else
            render 'new'
        end
    end
    
    def update
        if @user.update(user_params)
            flash[:notice] = "The profile was updated successfully."
            redirect_to @user
        else
            render 'edit'
        end
    end
    
    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all associated posts successfully deleted"
        redirect_to posts_path
    end
    
    private

    def set_user
        @user = User.find(params[:id])
    end
    
    def user_params
        params.require(:user).permit(:username, :fullname, :user_email, :password)
    end
    
    def require_same_user
        if current_user != @user && !!current_user.admin?
            flash[:alert] = "You can only edit or delete your own account"
            redirect_to @user
        end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    
    def gravatar_for(user, options = {size: 80})
        if user.user_email == nil
            return
        end
        email_address = user.user_email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(image_src, alt: user.username, class: "rounde shadow mx-auto d-block mt-2")
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_bottom_bar.html.erb
<footer id="sticky-footer" class="fixed-bottom py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Mashrur Hossain", "https://mashrurhossain.com", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible">
      <%= msg %>
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    </div>
  <% end %> 
</div>

app/views/layouts/_top_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Find Tutors</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active", id: "logo" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Tutors", users_path, class: "nav-link" %>
        </li>
        <li>
          <%= link_to "Posts", posts_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li>
            <%= link_to "Create New Post", new_post_path, class: "nav-link" %>
          </li>
        <% end %>
        
        <% if logged_in? %>
          <li class="nav-item">
            <% if current_user.admin? %>
              <%= link_to "(Admin) Profile - " + current_user.username, edit_user_path(current_user), class: "nav-link" %>
            <% else %>
              <%= link_to "Profile - " + current_user.username, edit_user_path(current_user), class: "nav-link" %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      
      <%= form_tag 'search', class: "d-flex", method: :get do %>
        <%= text_field_tag :keyword, params[:post], placeholder: "Key word", autofocus: true, class: "form-control me-2" %>
        <%= button_tag type: :submit, class: "btn btn-outline-success" do %>
          <%= 'Search' %>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Find Tutors</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Warning !! ensure that "stylesheet_pack_tag" is used, line below -->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">

    <%= render 'layouts/top_bar' %>
    
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-5" id="home-container">
  <div class="jumbotron text-center">
    <h1 class="display-4">Find Your Tutor for your final fight</h1>
    <p class="lead mt-4">This is the place for you to find your tutor and assist you to learn deeply, prepare thoroughly and score higher.</p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group mb-3">
    <%= label :post, :title, 'Title', :class => 'col-form-label' %>
    <%= text_field :post, :title, :class => 'form-control' %>
    
    <%= label :post, :tutor_area, 'Tutor Area', :class => 'col-form-label' %>
    <%= text_field :post, :tutor_area, :class => 'form-control' %>
    
    <%= label :post, :schedule, 'Schedule', :class => 'col-form-label' %>
    <%= text_field :post, :schedule, :class => 'form-control' %>
    
    <%= label :post, :description, 'Description', :class => 'col-form-label' %>
    <%= text_area :post, :description, :class => 'form-control' %>
    
    <%= label :post, :price, 'Price', :class => 'col-form-label' %>
    <%= text_field :post, :price, :class => 'form-control' %>
  </div>

  
  <%= form.submit :class => 'btn btn-success' %>
  <%= link_to 'Cancel', posts_path, :class => 'btn btn-danger' %>
  
<% end %>

app/views/posts/_post.html.erb
<div class="container">
  <% @posts.each do |post| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if post.user %>
              by <%= link_to post.user.username, user_path(post.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to post.title, post_path(post), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(post.description, length: 100) %></p>
            <%= link_to "View", post_path(post), class: "btn btn-outline-primary" %>
            <% if logged_in? && (post.user == current_user || current_user.admin?)  %>
              <%= link_to "Edit", edit_post_path(post), class: "btn btn-outline-success" %>
              <%= link_to "Delete", post_path(post), class: "btn btn-outline-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(post.created_at) %> ago, 
            edited <%= time_ago_in_words(post.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_user.html.erb
<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= user.fullname %>
          </div>
          <%= gravatar_for user, size: 120 %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to user.username, user_path(user), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(user.user_email, length: 100) %></p>
            <%= link_to "View Profile", user_path(user), class: "btn btn-outline-primary" %>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-outline-success" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete User", user_path(user), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure you want to delete the user and all associted posts?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago, 
            edited <%= time_ago_in_words(user.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/home.html.erb
<div class="container mt-5" id="home-container">
  <div class="jumbotron text-center">
    <h1 class="display-4">Find Your Tutor for your final fight</h1>
    <p class="lead mt-4">This is the place for you to find your tutor and assist you to learn deeply, prepare thoroughly and score higher.</p>
  </div>
</div>

<h1 class="text-center mt-4">Our recent posts</h1>

<%= render 'post' %>

app/views/posts/index.html.erb
<h1 class="text-center mt-4">Posts</h1>

<!--<table class="table table-striped table-dark table-hover">-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th scope="col">Title</th>-->
<!--      <th scope="col">Tutor Area</th>-->
<!--      <th scope="col">Schedule</th>-->
<!--      <th scope="col">Description</th>-->
<!--      <th scope="col">Price</th>-->
<!--      <th scope="col" colspan="3">Actions</th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <% @posts.each do |post| %>-->
<!--      <tr>-->
<!--        <td><%= post.title %></td>-->
<!--        <td><%= post.tutor_area %></td>-->
<!--        <td><%= post.schedule %></td>-->
<!--        <td><%= post.description %></td>-->
<!--        <td><%= post.price %></td>-->
<!--        <td><%= link_to 'Show', post %></td>-->
<!--        <td><%= link_to 'Edit', edit_post_path(post) %></td>-->
<!--        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
<!--</table>-->

<%= render 'post' %>

app/views/posts/new.html.erb
<div class="container mt-5">
    <h1 class="text-center">New Post</h1>

    <%= render 'form', post: @post %>
    </div>

app/views/posts/search.html.erb
<h1 class="text-center mt-4">Search Result</h1>

<%= render 'post' %>

<%= render 'user' %>

<div class="container col-6 mt-5">
    <% if @posts.blank? && @users.blank? %>
        <div class="alert alert-primary">
            <h4 class="alert-heading">No such results</h4>
            <p class="mb-0">Please use other key words to search</p>
        </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<h2 class="text-center mt-4"><%= @post.title %></h2>


<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= @post.user.username if @post.user %>
          <%= link_to gravatar_for(@post.user), user_path(@post.user) %>
        </div>
        <div class="card-body">
          <div class="card-text mb-2 text-left text-muted">Tutor Area: <%= @post.tutor_area %></div>
          <div class="card-text mb-2 text-left text-muted">Price: <%= @post.price %></div>
          <div class="card-text mb-2 text-left text-muted">Schedule: <%= @post.schedule %></div>
          <div class="card-text mb-2 text-left text-muted"><%= simple_format(@post.description) %></div>
          <% if logged_in? && (@post.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_post_path(@post), class: "btn btn-outline-info" %>
            <%= link_to "Delete", post_path(@post), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@post.created_at) %> ago, 
          edited <%= time_ago_in_words(@post.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/test.html.erb
<h1> this is for test</h1>
<%= form_with url: url_for(:controller => 'posts', :action => 'search') do |form| %>
    <%= form.label :query, "Search for:" %>
    <%= form.text_field :query %>
    <%= form.submit "Search" %>
<% end %>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/error', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: " col-form-label" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>
        
        <div class="form-group row">
          <%= f.label :fullname, class: " col-form-label" %>
          <div class="col-10">
            <%= f.text_field :fullname, class: "form-control shadow rounded", placeholder: "Enter a full name" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-form-label" %>
          <div class="col-10"> 
            <%= f.email_field :user_email, class: "form-control shadow rounded", placeholder: "Enter your email address. Please go to \"https://en.gravatar.com/\" to register your image." %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-form-label" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>

        <div class="form-group justify-content-center mt-4">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-success") %>
          <%= link_to 'Cancel', users_path, :class => 'btn btn-danger' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="container text-center mt-5 mb-5">Edit Profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4 mb-5">The Great Tutors</h1>

<%= render 'user' %>

app/views/users/new.html.erb
<h1 class="container text-center mt-5 mb-5 text-success">Signup</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-5 mb-5"><%= @user.fullname %>'s Profile</h1>

<%= gravatar_for @user, size: 200 %>

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-body">
                    <div class="card-text mb-2 text-left text-muted">Name: <%= @user.fullname %></div>
                    <div class="card-text mb-2 text-left text-muted">Email: <%= @user.user_email %></div>
                </div>
            </div>
        </div>
    </div>

    <h3 class="text-center mt-4">Posts</h3>
    <%= render 'posts/post' %>
    <% if logged_in? and @user == current_user %>
        <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-outline-success" %>
    <% end %>
</div>